sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    access-key-id: LTAI5tJkRr7HgHoSsXmpw9y6
    access-key-secret: 9S3XtYi4iygG2EDSdtQ1zYbBvk8cqK
    endpoint: oss-cn-heyuan.aliyuncs.com
    bucket-name: boardroptest
  redis:
    host: localhost
    port: 6379
    password: titi
    database: 0
  wechat:
    appid: wxb7779d2289c76657
    secret: f320b3cf58083a6381e624a13f6373a9